drop table if exists duck cascade;
drop table if exists pond cascade;
create table duck (
    id bigint generated by default as identity,
    age integer not null check (
        age >= 0
        AND age <= 30
    ),
    colour varchar(255) not null,
    habitat varchar(255) not null,
    duck_name varchar(55) not null,
    pond_id bigint,
    primary key (id)
);
create table pond (
    id bigint generated by default as identity,
    name varchar(255),
    primary key (id)
);
alter table duck
add constraint UK_8ukhqdjo77r8249jx605je74m unique (duck_name);
alter table duck
add constraint FKt84cs5x5pu53f6mddkdxrhhv9 foreign key (pond_id) references pond on delete cascade;